sudo: false
language: java

addons:
  sonarcloud:
    organization: "sknull-github"
    token:
      secure: ""

jdk:
- openjdk12

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

script:
  - mvn clean verify

after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn coveralls:report
- mvn sonar:sonar -Dsonar.projectKey=sknull_solar-time -Dsonar.organization=sknull-github -Dsonar.host.url=https://sonarcloud.io
